name: build
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - name: Test
        run: |
          TF_ACC=1 go test ./... -v -trimpath -coverprofile=coverage.out
          go tool cover -func=coverage.out
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build -trimpath -o bin/terraform-provider-jwks .
